(merged (batch-id batch-001) (schema-id crane) (schema-version 0.1.0)
 (count 16)
 (requirements
  (requirement (id batch-001-0001) (display-id REQ-PERF-0001)
   (group performance)
   (text "The crane must lift the transformer, mass 8 t.")
   (source Contract-2026-014) (note "")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0002) (display-id REQ-PERF-0002)
   (group performance) (text "Load-capacity safety factor >= 1.25.")
   (source Internal-STD-07) (note "Bound to feature LoadCapacity")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0003) (display-id REQ-REG-0001)
   (group regulatory) (text "Certification per EN for Europe.")
   (source Regulation) (note "")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0004) (display-id REQ-ENV-0001)
   (group environmental)
   (text "Tropical climate for Thailand; ambient up to 45 degC.")
   (source Regulation) (note "")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0005) (display-id REQ-SAF-0001) (group safety)
   (text "Emergency stop shall halt all motion within 0.5 s.")
   (source Internal-STD-07) (note "")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0006) (display-id REQ-PURP-0001) (group purpose)
   (text "lift lift and lift") (source "contract #1") (note "all is good")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0007) (display-id REQ-SAF-0002) (group safety)
   (text "444 v") (source "contract #7") (note "yes and no")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0008) (display-id REQ-ENV-0002)
   (group environmental) (text 45~dd) (source "contract #5") (note 333)
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0009) (display-id REQ-FUNC-0001)
   (group functional) (text 100%) (source "contract #2")
   (note "all is good all is good")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0010) (display-id REQ-IFC-0001)
   (group interface) (text "a lot") (source "contract #6") (note 34#4ff)
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0011) (display-id REQ-PERF-0003)
   (group performance) (text "ffjjf , dd< sss > ddd") (source "contract #3")
   (note "all is good,,,,")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0012) (display-id REQ-MFG-0001)
   (group manufacturing) (text none) (source "contract #9") (note llfkkf)
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0013) (display-id REQ-TEST-0001) (group testing)
   (text "not pplicable") (source "contract #8") (note "nd ddd")
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0014) (display-id REQ-REG-0002)
   (group regulatory) (text /><4) (source "contract #4") (note ddd)
   (headers
    ((author alice@example.com) (system-name "Main crane") (rds RDS-001)
     (rds-pp RDS-PP-001))))
  (requirement (id batch-001-0015) (display-id REQ-PURP-0002) (group purpose)
   (text "dddd Lift all what it can") (source "Internal Company")
   (note Mandatory)
   (headers
    ((author ipol@dddd.com) (system-name "Main crane") (rds =N1)
     (rds-pp =KKK))))
  (requirement (id batch-001-0016) (display-id REQ-FUNC-0002)
   (group functional) (text "Have a cabin") (source "Good will")
   (note Optional)
   (headers
    ((author ipol@dddd.com) (system-name "Main crane") (rds =N1)
     (rds-pp =KKK))))))
