(executable
 (name main)
 (modes js)
 (libraries reqlib sexplib js_of_ocaml)
 (preprocess (pps js_of_ocaml-ppx)))   ; <-- add this line

(rule
 (target schema_data.ml)
 (deps ../schemas/example.v1.sexp)
 (action
  (with-stdout-to schema_data.ml
   (progn
    (echo "let text = {|\n")
    (cat ../schemas/example.v1.sexp)
    (echo "|}\n")))))